# Mora, Justie Renzo B
# 2ECE - B

In [3]:
import pandas as pd

### **A. Positional and Label-Based Slicing**

#### a. Display shape and complete list of column names

In [4]:
cars = pd.read_csv('cars.csv')

In [5]:
print("Shape of DataFrame:", cars.shape)
print("Columns in DataFrame:", cars.columns.tolist())

Shape of DataFrame: (32, 12)
Columns in DataFrame: ['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

#### b. Using positional slicing, create cars 6 to 10 containing rows 6 through 10 of the dataset, where the first data row is row 1.

In [6]:
cars_6_to_10 = cars.iloc[5:10]
display(cars_6_to_10)

        Model   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
5     Valiant  18.1    6  225.0  105  2.76  3.46  20.22   1   0     3     1
6  Duster 360  14.3    8  360.0  245  3.21  3.57  15.84   0   0     3     4
7   Merc 240D  24.4    4  146.7   62  3.69  3.19  20.00   1   0     4     2
8    Merc 230  22.8    4  140.8   95  3.92  3.15  22.90   1   0     4     2
9    Merc 280  19.2    6  167.6  123  3.92  3.44  18.30   1   0     4     4

#### c. From cars 6 to 10, display only the columns Model, mpg, cyl, hp, and gear, in that order.

In [7]:
selected_columns = cars_6_to_10[['Model', 'mpg', 'cyl', 'hp', 'gear']]
display(selected_columns)

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

### **B. Model Lookup**

#### a. Display the complete row for Toyota Corolla.

In [8]:
toyota = cars[cars['Model'] == 'Toyota Corolla']
display(toyota)

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

#### b. For Pontiac Firebird, display only Model, mpg, hp, and wt.

In [9]:
pontiac = cars[cars['Model'] == 'Pontiac Firebird'][['Model', 'mpg', 'hp', 'wt']]
display(pontiac)

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

### **C. Multi-Model Subsetting**

In [25]:
selected_cars = cars[(cars['Model'] == 'Datsun 710') |
                     (cars['Model'] == 'Lotus Europa') |
                     (cars['Model'] == 'Ferrari Dino')][['Model', 'mpg', 'cyl', 'hp', 'gear']]
display(selected_cars)

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

In [26]:
print("Shape of selected_cars:", selected_cars.shape)

Shape of selected_cars: (3, 5)